"""initial kindle catalog schema

Revision ID: 2344a4d50919
Revises:
Create Date: 2026-07-25 16:29:11.867505
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "2344a4d50919"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_name_key"), "authors", ["name_key"], unique=True)
    op.create_table(
        "books",
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title_normalized", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isbn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isbn13", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("book_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kindle_acquisition_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_reading_ms", sa.Integer(), nullable=True),
        sa.Column("last_read_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("asin"),
    )
    op.create_index(op.f("ix_books_book_type"), "books", ["book_type"], unique=False)
    op.create_index(op.f("ix_books_category"), "books", ["category"], unique=False)
    op.create_index(op.f("ix_books_is_completed"), "books", ["is_completed"], unique=False)
    op.create_index(op.f("ix_books_kindle_acquisition_date"), "books", ["kindle_acquisition_date"], unique=False)
    op.create_index(op.f("ix_books_title_normalized"), "books", ["title_normalized"], unique=False)
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("files_processed", sa.Integer(), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_runs_source_kind"), "import_runs", ["source_kind"], unique=False)
    op.create_index(op.f("ix_import_runs_status"), "import_runs", ["status"], unique=False)
    op.create_table(
        "imported_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("imported_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_kind", "filename", "sha256"),
    )
    op.create_index(op.f("ix_imported_files_source_kind"), "imported_files", ["source_kind"], unique=False)
    op.create_index(op.f("ix_imported_files_status"), "imported_files", ["status"], unique=False)
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "author_key"),
    )
    op.create_index(op.f("ix_series_name"), "series", ["name"], unique=False)
    op.create_table(
        "book_authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asin", "author_id"),
    )
    op.create_index(op.f("ix_book_authors_asin"), "book_authors", ["asin"], unique=False)
    op.create_index(op.f("ix_book_authors_author_id"), "book_authors", ["author_id"], unique=False)
    op.create_table(
        "book_genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asin", "genre"),
    )
    op.create_index(op.f("ix_book_genres_asin"), "book_genres", ["asin"], unique=False)
    op.create_index(op.f("ix_book_genres_genre"), "book_genres", ["genre"], unique=False)
    op.create_table(
        "book_series",
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("volume_number", sa.Float(), nullable=True),
        sa.Column("volume_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detection_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_manually_edited", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("asin"),
    )
    op.create_index(op.f("ix_book_series_series_id"), "book_series", ["series_id"], unique=False)
    op.create_table(
        "borrowings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("authors", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("loan_program", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("loan_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("loan_creation_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("loan_acceptance_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("end_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["imported_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asin", "loan_creation_date"),
    )
    op.create_index(op.f("ix_borrowings_asin"), "borrowings", ["asin"], unique=False)
    op.create_index(op.f("ix_borrowings_loan_creation_date"), "borrowings", ["loan_creation_date"], unique=False)
    op.create_index(op.f("ix_borrowings_loan_status"), "borrowings", ["loan_status"], unique=False)
    op.create_table(
        "capture_jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_screens", sa.Integer(), nullable=True),
        sa.Column("requested_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("claimed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("book_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("captured_screens", sa.Integer(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_capture_jobs_agent_id"), "capture_jobs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_capture_jobs_asin"), "capture_jobs", ["asin"], unique=False)
    op.create_index(op.f("ix_capture_jobs_source"), "capture_jobs", ["source"], unique=False)
    op.create_index(op.f("ix_capture_jobs_status"), "capture_jobs", ["status"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("order_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("digital_order_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["imported_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number", "asin", "title"),
    )
    op.create_index(op.f("ix_purchases_asin"), "purchases", ["asin"], unique=False)
    op.create_index(op.f("ix_purchases_order_date"), "purchases", ["order_date"], unique=False)
    op.create_index(op.f("ix_purchases_order_number"), "purchases", ["order_number"], unique=False)
    op.create_index(op.f("ix_purchases_order_status"), "purchases", ["order_status"], unique=False)
    op.create_table(
        "returns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refund_amount", sa.Integer(), nullable=True),
        sa.Column("return_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("return_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asin"],
            ["books.asin"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["imported_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asin", "order_id", "return_date"),
    )
    op.create_index(op.f("ix_returns_asin"), "returns", ["asin"], unique=False)
    op.create_index(op.f("ix_returns_order_id"), "returns", ["order_id"], unique=False)
    op.create_index(op.f("ix_returns_return_date"), "returns", ["return_date"], unique=False)
    op.create_table(
        "series_subscriptions",
        sa.Column("series_asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("resolution_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("imported_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("series_asin"),
    )
    op.create_index(op.f("ix_series_subscriptions_series_id"), "series_subscriptions", ["series_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_series_subscriptions_series_id"), table_name="series_subscriptions")
    op.drop_table("series_subscriptions")
    op.drop_index(op.f("ix_returns_return_date"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_asin"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_purchases_order_status"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_order_number"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_order_date"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_asin"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_capture_jobs_status"), table_name="capture_jobs")
    op.drop_index(op.f("ix_capture_jobs_source"), table_name="capture_jobs")
    op.drop_index(op.f("ix_capture_jobs_asin"), table_name="capture_jobs")
    op.drop_index(op.f("ix_capture_jobs_agent_id"), table_name="capture_jobs")
    op.drop_table("capture_jobs")
    op.drop_index(op.f("ix_borrowings_loan_status"), table_name="borrowings")
    op.drop_index(op.f("ix_borrowings_loan_creation_date"), table_name="borrowings")
    op.drop_index(op.f("ix_borrowings_asin"), table_name="borrowings")
    op.drop_table("borrowings")
    op.drop_index(op.f("ix_book_series_series_id"), table_name="book_series")
    op.drop_table("book_series")
    op.drop_index(op.f("ix_book_genres_genre"), table_name="book_genres")
    op.drop_index(op.f("ix_book_genres_asin"), table_name="book_genres")
    op.drop_table("book_genres")
    op.drop_index(op.f("ix_book_authors_author_id"), table_name="book_authors")
    op.drop_index(op.f("ix_book_authors_asin"), table_name="book_authors")
    op.drop_table("book_authors")
    op.drop_index(op.f("ix_series_name"), table_name="series")
    op.drop_table("series")
    op.drop_index(op.f("ix_imported_files_status"), table_name="imported_files")
    op.drop_index(op.f("ix_imported_files_source_kind"), table_name="imported_files")
    op.drop_table("imported_files")
    op.drop_index(op.f("ix_import_runs_status"), table_name="import_runs")
    op.drop_index(op.f("ix_import_runs_source_kind"), table_name="import_runs")
    op.drop_table("import_runs")
    op.drop_index(op.f("ix_books_title_normalized"), table_name="books")
    op.drop_index(op.f("ix_books_kindle_acquisition_date"), table_name="books")
    op.drop_index(op.f("ix_books_is_completed"), table_name="books")
    op.drop_index(op.f("ix_books_category"), table_name="books")
    op.drop_index(op.f("ix_books_book_type"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_authors_name_key"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
