"""既存importを維持するprompt互換facade。"""

from .character_prompts import CHARACTER_FACT_EXTRACTION_PROMPT as CHARACTER_FACT_EXTRACTION_PROMPT
from .grounding_prompts import GROUNDING_OPTIONS as GROUNDING_OPTIONS
from .grounding_prompts import SUMMARY_GROUNDING_PROMPT as SUMMARY_GROUNDING_PROMPT
from .grounding_prompts import SUMMARY_GROUNDING_REPAIR_PROMPT as SUMMARY_GROUNDING_REPAIR_PROMPT
from .summary_prompts import CATALOG_SUMMARY_EDITOR_PROMPT as CATALOG_SUMMARY_EDITOR_PROMPT
from .summary_prompts import CATALOG_SUMMARY_FROM_FACTS_PROMPT as CATALOG_SUMMARY_FROM_FACTS_PROMPT
from .summary_prompts import CATALOG_SUMMARY_MAX_CHARS as CATALOG_SUMMARY_MAX_CHARS
from .summary_prompts import CATALOG_SUMMARY_MIN_CHARS as CATALOG_SUMMARY_MIN_CHARS
from .summary_prompts import CATALOG_SUMMARY_OPTIONS as CATALOG_SUMMARY_OPTIONS
from .summary_prompts import COMBINED_MAX_CHARACTERS as COMBINED_MAX_CHARACTERS
from .summary_prompts import COMBINED_OPTIONS as COMBINED_OPTIONS
from .summary_prompts import COMBINED_PROMPT as COMBINED_PROMPT
from .summary_prompts import FACT_CHUNK_MAX_CHARS as FACT_CHUNK_MAX_CHARS
from .summary_prompts import FACT_EXTRACTION_OPTIONS as FACT_EXTRACTION_OPTIONS
from .summary_prompts import FACT_EXTRACTION_PROMPT as FACT_EXTRACTION_PROMPT
from .summary_prompts import MAP_CHUNK_TARGET_CHARS as MAP_CHUNK_TARGET_CHARS
from .summary_prompts import MAP_MAX_CHUNKS as MAP_MAX_CHUNKS
from .summary_prompts import MAP_OPTIONS as MAP_OPTIONS
from .summary_prompts import MAP_PROMPT as MAP_PROMPT
from .summary_prompts import ONE_SHOT_MAX_BODY_CHARS as ONE_SHOT_MAX_BODY_CHARS
from .summary_prompts import ONE_SHOT_OPTIONS as ONE_SHOT_OPTIONS
from .summary_prompts import PROSE_EDITOR_OPTIONS as PROSE_EDITOR_OPTIONS
from .summary_prompts import PROSE_EDITOR_PROMPT as PROSE_EDITOR_PROMPT
from .summary_prompts import REDUCE_OPTIONS as REDUCE_OPTIONS
from .summary_prompts import REDUCE_PROMPT as REDUCE_PROMPT
from .summary_prompts import SINGLE_PROMPT as SINGLE_PROMPT
from .summary_prompts import SUMMARY_FROM_FACTS_PROMPT as SUMMARY_FROM_FACTS_PROMPT
from .summary_prompts import parse_combined_output as parse_combined_output

__all__ = [
    "CATALOG_SUMMARY_EDITOR_PROMPT",
    "CATALOG_SUMMARY_FROM_FACTS_PROMPT",
    "CATALOG_SUMMARY_MAX_CHARS",
    "CATALOG_SUMMARY_MIN_CHARS",
    "CATALOG_SUMMARY_OPTIONS",
    "CHARACTER_FACT_EXTRACTION_PROMPT",
    "COMBINED_MAX_CHARACTERS",
    "COMBINED_OPTIONS",
    "COMBINED_PROMPT",
    "FACT_CHUNK_MAX_CHARS",
    "FACT_EXTRACTION_OPTIONS",
    "FACT_EXTRACTION_PROMPT",
    "GROUNDING_OPTIONS",
    "MAP_CHUNK_TARGET_CHARS",
    "MAP_MAX_CHUNKS",
    "MAP_OPTIONS",
    "MAP_PROMPT",
    "ONE_SHOT_MAX_BODY_CHARS",
    "ONE_SHOT_OPTIONS",
    "PROSE_EDITOR_OPTIONS",
    "PROSE_EDITOR_PROMPT",
    "REDUCE_OPTIONS",
    "REDUCE_PROMPT",
    "SINGLE_PROMPT",
    "SUMMARY_FROM_FACTS_PROMPT",
    "SUMMARY_GROUNDING_PROMPT",
    "SUMMARY_GROUNDING_REPAIR_PROMPT",
    "parse_combined_output",
]
